poversion: "3.8"
services:
  db:
    container_name: pgis
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_DB: citygerdb
      POSTGRES_PASSWORD: mypassword
    ports:
      - 5000:5432
    volumes:
      - ../../pgdata:/var/lib/postgresql/data
